### ISSUE TITLE
Add a license to code sample

### ISSUE THREAD

**Issue by remyleone** [grpc-up-and-running/samples#19]
Hello, 

Could you add a license to the content of this repository? https://choosealicense.com/

**Comment by jimbeveridge** [comment]
+1. There's verbiage in the book about code reuse, but it's not a proper license that our lawyers will approve. Please consider adding a LICENSE file to the repo that grants an Apache or an MIT license.

IANAL, but a license also benefits you because it limits your liability.

**Comment by daneshk** [comment]
Thanks, @remyleone and @jimbeveridge for the input. I added Creative Commons License[1]

1. https://creativecommons.org/licenses/by/4.0/
