### ISSUE TITLE
protoc command ch02\productinfo\go\README.md uses wrong .proto file

### ISSUE THREAD

**Issue by jimbeveridge** [grpc-up-and-running/samples#21]
The file `ch02\productinfo\go\README.md` shows the `protoc` command to be:
``` 
protoc -I proto/ proto/order_management.proto --go_out =plugins=grpc:service-gen
``` 

This command should refer to `product_info.proto` instead of to `order_management.proto`.

There's a second problem here that generated file ends up in the wrong directory. To make this command work, you have to run `proto` when your current directory is `ch02/productinfo`. However, that will put the result file in the wrong place and the instructions don't describe how to fix the problem.

I noticed that you've pregenerated the .proto.go files, but if you want readers to depend on them, then please update the README.md files appropriately.

**Comment by daneshk** [comment]
Thanks a lot, @jimbeveridge for raising the issue. I will fix them asap
