### ISSUE TITLE
Most GO Examples can't be compiled

### ISSUE THREAD

**Issue by rwellinger** [grpc-up-and-running/samples#47]
The book so far is ok. But the examples most are not running. Special the GO examples. Not able to compile any proto files and no examples too. Description with the command in the README.md files ar not working most. So many errors. Terrible, sorry guys.

**Comment by xlzhangkeke** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by rwellinger** [comment]
Oh wow ... can someone translate that :)

**Comment by rwellinger** [comment]
Was my fault. The only thing not working is generate the stubs fro GO. But I think this is because the samples was build with older version.

protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative product_info.proto

And inside the proto file:

option go_package = "..."

after this changes it works for me.
